### ISSUE TITLE
Cool project

### ISSUE THREAD

**Issue by firmai** [nicolay-r/AREkit#414]
This project is great, slightly too hard for me to understand, as I am not an expert in relational sentiment. It would be great to have a simple tutorial on a financial news dataset to understand exactely how this works. Thanks for your hard work in open sourcing this!

**Comment by nicolay-r** [comment]
Hello @firmai and nice to meet you at first! 

Thank you for letting me know you feedback on so.

>  It would be great to have a simple tutorial on a financial news dataset to understand exactely how this works. 
Besides the [complete journey of the tutorials](https://github.com/nicolay-r/AREkit/tree/master/tests/tutorials), for now I can navigate you to the project/demo which goes in parallel with this one in terms of the compatibility and development, and the latter dubbed as [ARElight](https://github.com/nicolay-r/AREkit/tree/master/tests/tutorials). 
The latter provides [instant inference](https://github.com/nicolay-r/ARElight#inference), based on the pre-trained BERT model (support only Russian language due to the specifics of the studies)

However, considering your question as a potential request for a further post/colab notebook on so.

**Comment by firmai** [comment]
@nicolay-r thanks for the reply! A colab notebook would make it 10 times more ingestible for me, I am a bit of a dumb dumb. Thanks :)

**Comment by nicolay-r** [comment]
Okay, got your point and head to the notebook tutorials as well. I can't guarantee the latter to be provided in short, since this is not the urgent task expected to be considered according to the personal roadmap, but looking forward to address on so within the next/upcomming release

**Comment by nicolay-r** [comment]
@firmai, apologies for a question aside of the following issue, but I'm wonder is it possible to reach you out by email mentioned on github page? (Email question a while ago)  Thank you!
